base_url = "/"

author = "thatoddshade"
title = "thatoddshade’s palace"
description = "The gloomy agony that shines in rooms of pine and ebony…"
default_language = "en"

compile_sass = true
minify_html = true
ignored_static = ["*.xcf"]

[markdown]
highlight_code = true
highlight_theme = "1337"

[extra]
domain = "thatoddshade.is-a.dev"

homepage_links = [
	{ name = "home", url = "@/_index.md" },
	#{ name = "slipbox", url = "@/slipbox/_index.md" },
	{ name = "posts", url = "@/posts/_index.md" },
	{ name = "now", url = "@/now.md" },
	#{ name = "blogroll", url = "@/blogroll.md" },
	#{ name = "people", url = "@/people.md" },
	#{ name = "uses", url = "@/uses.md" },
	#{ name = "colophon", url = "@/colophon.md" },
	{ name = "about", url = "@/about.md" },
]

hfeed = "/posts"

email = "thatoddshade@gmx.com"

links = [
	{ name = "Pocket", url = "https://getpocket.com/@32bp8T96AaK76da688g29b3ge3d0A226093YQ7v348H420l3636f9k94U50tF45f?src=navbar", inactive = true},
	{ name = "GitHub", url = "https://github.com/thatoddshade", lang = "en" },
	{ name = "Discord", url = "https://discord.com/users/1015587533939298316" },
	{ name = "itch.io", url = "https://thatoddshade.itch.io/", lang = "en"},
	{ name = "YouTube", url = "https://www.youtube.com/@thatoddshade" },
	{ name = "Reddit", url = "https://www.reddit.com/user/That-Odd-Shade/", lang = "en" },
	{ name = "Modrinth", url = "https://modrinth.com/user/thatoddshade", lang = "en" },
	{ name = "Stack Overflow", url = "https://stackoverflow.com/users/20547839/thatoddshade" },
	{ name = "Gravatar", url = "https://gravatar.com/thatoddshade", inactive = true },
	{ name = "OpenStreetMap", url = "https://www.openstreetmap.org/user/thatoddshade" },
	{ name = "Art Fight", url = "https://artfight.net/~thatoddshade"},
	{ name = "mastodon.art", url = "https://mastodon.art/@thatoddshade", lang = "en", inactive = true },
	{ name = "SourceHut", url = "https://sr.ht/~thatoddshade/", lang = "en" },
	{ name = "imood.com", url = "https://imood.com/users/thatoddshade", lang = "en"},
	{ name = "Wikipédia (fr)", url = "https://fr.wikipedia.org/wiki/Utilisateur:Thatoddshade", lang = "fr" },
	{ name = "Wikipedia (en)", url = "https://en.wikipedia.org/wiki/User:Thatoddshade", lang = "en" },
	{ name = "Tumblr", url = "https://www.tumblr.com/blog/thatoddshade" },
	{ name = "last.fm", url = "https://www.last.fm/user/thatoddshade" },
	{ name = "doevery.day", url = "https://doevery.day/thatoddshade", lang = "en", inactive = true},
	{ name = "Internet Archive", url = "https://archive.org/details/@thatoddshade", lang = "en" },
	{ name = "Postcrossing", url = "https://www.postcrossing.com/user/thatoddshade" },
	{ name = "mas.to", url = "https://mas.to/@thatoddshade", lang = "en" },
	{ name = "lipu pona", url = "https://lipupona.net/ijosata", lang = "tok"},
]

imood_username = "thatoddshade"
mastodon_username = "@thatoddshade@mas.to"

photo = "/favicon.png"
favicons = [
	{ rel="shortcut icon", href = "/favicon.ico", type = "image/x-icon" },

	{ rel="apple-touch-icon", type = "image/png", sizes="120x120", href = "/favicon-120x120.png" },
	{ rel="apple-touch-icon", type = "image/png", sizes="152x152", href = "/favicon-152x152.png" },
	{ rel="apple-touch-icon", type = "image/png", sizes="167x167", href = "/favicon-167x167.png" },
	{ rel="apple-touch-icon", type = "image/png", sizes="180x180", href = "/favicon-180x180.png" },

	{ rel="icon", sizes="400x400", href = "/favicon.jpeg", type = "image/jpeg" },
	{ rel="icon", sizes="400x400", href = "/favicon.png", type = "image/png" },
]

# appended between a `page.title` and `config.title`
title_separator = " ⸺:⸺ "
