base_url = "/"

title = "thatoddshade’s palace"
description = "The gloomy agony that shines in rooms of pine and ebony…"
author = "thatoddshade"
default_language = "en"

compile_sass = true
minify_html = true
ignored_static = ["*.xcf"]

[markdown]
highlight_code = true
highlight_theme = "1337"

[extra]
homepage_links = [
	{ title = "home", href = "@/_index.md" },
	{ title = "slipbox", href = "@/slipbox/_index.md" },
	{ title = "posts", href = "@/posts/_index.md" },
	{ title = "blogroll", href = "@/blogroll.md" },
	{ title = "people", href = "@/people.md" },
	{ title = "uses", href = "@/uses.md" },
	{ title = "colophon", href = "@/colophon.md" },
	{ title = "about", href = "@/about.md" },
]

hfeed = "/posts"

email = "thatoddshade@gmx.com"

links = [
	{ name = "Pocket", url = "https://getpocket.com/@32bp8T96AaK76da688g29b3ge3d0A226093YQ7v348H420l3636f9k94U50tF45f?src=navbar", inactive = true},
	{ name = "GitHub", url = "https://github.com/thatoddshade", lang = "en" },
	{ name = "Discord", url = "https://discord.com/users/1015587533939298316" },
	{ name = "itch.io", url = "https://thatoddshade.itch.io/", lang = "en"},
	{ name = "YouTube", url = "https://www.youtube.com/@thatoddshade" },
	{ name = "Reddit", url = "https://www.reddit.com/user/That-Odd-Shade/", lang = "en" },
	{ name = "Modrinth", url = "https://modrinth.com/user/thatoddshade", lang = "en" },
	{ name = "Stack Overflow", url = "https://stackoverflow.com/users/20547839/thatoddshade" },
	{ name = "Gravatar", url = "https://gravatar.com/thatoddshade", inactive = true },
	{ name = "OpenStreetMap", url = "https://www.openstreetmap.org/user/thatoddshade" },
	{ name = "Art Fight", url = "https://artfight.net/~thatoddshade"},
	{ name = "mastodon.art", url = "https://mastodon.art/@thatoddshade", lang = "en", inactive = true },
	{ name = "SourceHut", url = "https://sr.ht/~thatoddshade/", lang = "en" },
	{ name = "imood.com", url = "https://imood.com/users/thatoddshade", lang = "en"},
	{ name = "Wikipédia (fr)", url = "https://fr.wikipedia.org/wiki/Utilisateur:Thatoddshade", lang = "fr" },
	{ name = "Wikipedia (en)", url = "https://en.wikipedia.org/wiki/User:Thatoddshade", lang = "en" },
	{ name = "Tumblr", url = "https://www.tumblr.com/blog/thatoddshade" },
	{ name = "last.fm", url = "https://www.last.fm/user/thatoddshade" },
	{ name = "doevery.day", url = "https://doevery.day/thatoddshade", lang = "en"},
	{ name = "Internet Archive", url = "https://archive.org/details/@thatoddshade", lang = "en" },
	{ name = "Postcrossing", url = "https://www.postcrossing.com/user/thatoddshade" },
	{ name = "mas.to", url = "https://mas.to/@thatoddshade", lang = "en" },
	{ name = "lipu pona", url = "https://lipupona.net/ijosata", lang = "tok"},
]

imood_username = "thatoddshade"
mastodon_username = "@thatoddshade@mas.to"

photo = "/images/photo.svg"

# appended between a `page.title` and `config.title`
title_separator = " — "
